image: abstruse

matrix:
  - env: SCRIPT=test NODE_VERSION=10

before_install:
  - nvm install $NODE_VERSION
  - npm config set spin false
  - npm config set progress false

install:
  - npm install

script:
  - if [[ "$SCRIPT" ]]; then npm run-script $SCRIPT; fi

cache:
  - node_modules