image: abstruse

matrix:
  - env: SCRIPT=test

before_install:
  - nvm install node
  - npm config set spin false
  - npm config set progress false

install:
  - npm install

script:
  - sleep 60
  - echo "Works!"
  - if [[ "$SCRIPT" ]]; then npm run-script $SCRIPT; fi

cache:
  - node_modules